parent=keycloak.v2
styles=css/styles.css
title=TrustDeck Administration
description=Administration Console for the TrustDeck identity and access management service.
logo=img/trustdeck-logo.svg
logoUrl=/
favicon=img/favicon.ico
faviconType=image/png
darkMode=false
contentHashPattern=assets/.*
