parent=keycloak.v3
styles=css/styles.css
title=TrustDeck Account
description=Manage your TrustDeck account, credentials, sessions and connected applications.
logo=img/trustdeck-logo.svg
logoUrl=/
favicon=img/favicon.ico
faviconType=image/png
darkMode=false
contentHashPattern=assets/.*
